import test from 'node:test';import assert from 'node:assert/strict';
import {EditingDocument} from '../dist/tactics/editor-3d-controller.js';
import {blankMap,parseMap,validateMap} from '../dist/tactics/core/maps.js';
import {createGame} from '../dist/tactics/core/engine.js';
import {characterDiagnostics,knownCharacterReferences} from '../dist/tactics/character-properties.js';
const doc=()=>new EditingDocument().open(JSON.stringify(blankMap('Characters')));
function place(d,x=10,tool='guard'){assert.ok(d.apply({tool,start:{x,y:10,z:0},options:{species:'donkey',weapon:'hands',outfit:'red-hats'}}).ok);return d.map.guards.at(-1).character.id;}
const edit=(d,id,character)=>d.updateCharacter(id,{character});
test('Red Hat can talk and sell independently; editing and renaming preserve identities and links',()=>{const d=doc(),a=place(d),b=place(d,12,'npc');edit(d,a,{displayName:'Trader',scriptId:'town_shopkeeper',faction:'red-hats',attitude:'friendly',canTalk:true,dialogueRef:'welcome',canSell:true,shopInventoryRef:'general_store',shopPricingRef:'normal_prices'});edit(d,b,{displayName:'Trader',references:[{role:'shop_partner',targetId:a}]});const prior=d.export();edit(d,a,{scriptId:'market_trader',displayName:'Market trader'});assert.equal(d.character(a).p.outfit,'red-hats');assert.equal(d.character(a).p.character.id,a);assert.equal(d.character(b).p.character.references[0].targetId,a);assert.equal(knownCharacterReferences(d.map,a)[0].role,'shop_partner');d.undo();assert.equal(d.export(),prior);d.redo();assert.equal(d.character(a).p.character.scriptId,'market_trader');});
test('character duplication remaps self-links and script IDs while keeping other targets',()=>{const d=doc(),a=place(d),b=place(d,12);edit(d,a,{scriptId:'guide',references:[{role:'self',targetId:a},{role:'friend',targetId:b}]});const copy=d.duplicateCharacter(a,{x:14,y:10,z:0}),c=d.character(copy).p.character;assert.notEqual(copy,a);assert.equal(c.scriptId,'guide_2');assert.deepEqual(c.references.map(r=>r.targetId),[copy,b]);assert.equal(d.character(a).p.character.scriptId,'guide');assert.throws(()=>d.duplicateCharacter(a,{x:14,y:10,z:0}),/Overlapping/);});
test('duplicated reusable blocks remap internal links, avoid collisions and carry resource catalogs',()=>{const d=doc(),a=place(d),b=place(d,12);edit(d,a,{scriptId:'guide',canTalk:true,dialogueRef:'welcome',references:[{role:'partner',targetId:b}]});edit(d,b,{scriptId:'partner',references:[{role:'guide',targetId:a}]});d.characterResources({dialogues:['welcome'],shopInventories:[],shopPricing:[]});const block=d.capture(0,0);d.place(block,1,0);d.place(block,2,0);const ids=d.map.guards.map(p=>p.character.id),names=d.map.guards.map(p=>p.character.scriptId);assert.equal(new Set(ids).size,6);assert.equal(new Set(names).size,6);for(const offset of [0,2,4]){const [x,y]=d.map.guards.slice(offset,offset+2);assert.equal(x.character.references[0].targetId,y.character.id);assert.equal(y.character.references[0].targetId,x.character.id);}assert.deepEqual(characterDiagnostics(d.map),[]);const reopened=new EditingDocument().open(JSON.stringify(block));assert.equal(reopened.map.guards[0].character.id,a);assert.equal(reopened.map.guards[0].character.references[0].targetId,b);});
test('save/export/import and playtest preserve hooks and IDs',()=>{const d=doc(),a=place(d);edit(d,a,{displayName:'Town guide',scriptId:'town_guide',canTalk:true,dialogueRef:'directions'});d.characterResources({dialogues:['directions']});const serialized=d.export(),reopened=new EditingDocument().open(serialized);assert.equal(reopened.export(),serialized);const runtime=createGame(1,parseMap(serialized),false),u=runtime.units.find(u=>u.characterId===a);assert.equal(u.name,'Town guide');assert.equal(u.character.dialogueRef,'directions');assert.equal(u.character.id,a);assert.equal(u.team,'guard');});
test('legacy maps keep character combat behavior and optional extra configuration',()=>{const m=blankMap();m.guards=[{x:10,y:10,species:'donkey',weapon:'hands',outfit:'red-hats'}];const old=createGame(1,m,false),d=new EditingDocument().open(JSON.stringify(m)),fresh=createGame(1,d.map,false);const state=s=>s.units.map(({team,name,species,weapon,hp,ap,state})=>({team,name,species,weapon,hp,ap,state}));assert.deepEqual(state(fresh),state(old));assert.equal(d.map.guards[0].character.canTalk,false);assert.equal(d.map.guards[0].character.attitude,'hostile');assert.equal(d.map.starts[0].character.attitude,'friendly');});
test('duplicate identities/script names and malformed hooks reject atomically; missing resources report clearly',()=>{const d=doc(),a=place(d),b=place(d,12);edit(d,a,{scriptId:'one',canTalk:true,canSell:true,dialogueRef:'absent',shopInventoryRef:'missing_inventory',shopPricingRef:'missing_prices',references:[{role:'quest_target',targetId:'char_missing'}]});const prior=d.export();assert.throws(()=>edit(d,b,{scriptId:'one'}),/duplicate Script ID/);assert.equal(d.export(),prior);assert.throws(()=>edit(d,b,{canTalk:'yes'}),/checkbox/);assert.equal(d.export(),prior);const errors=characterDiagnostics(d.map);assert.equal(errors.length,4);assert.ok(errors.some(e=>e.includes('missing character')));const raw=JSON.parse(prior);raw.guards[1].character.id=a;assert.ok(validateMap(raw).some(e=>e.includes('duplicate internal')));assert.throws(()=>parseMap(JSON.stringify(raw)),/duplicate internal/);});
test('squad character properties are editable without replacing the permanent slot identity',()=>{const d=doc(),id=d.map.starts[0].character.id;d.updateCharacter(id,{species:'donkey',outfit:'blue-hawaiian',weapon:'hands',character:{displayName:'Guide'}});assert.equal(d.map.starts.length,4);assert.equal(d.map.starts[0].character.id,id);const u=createGame(1,d.map,false).units[0];assert.equal(u.name,'Guide');assert.equal(u.species,'donkey');assert.equal(u.outfit,'blue-hawaiian');assert.equal(u.weapon,'hands');});

test('moving a squad start preserves its identity, properties and incoming references',()=>{const d=doc(),id=d.map.starts[0].character.id,g=place(d);edit(d,id,{scriptId:'leader',displayName:'Leader'});edit(d,g,{references:[{role:'leader',targetId:id}]});assert.ok(d.apply({tool:'squad',start:{x:20,y:20,z:0},options:{slot:0}}).ok);assert.equal(d.map.starts[0].character.id,id);assert.equal(d.map.starts[0].character.scriptId,'leader');assert.equal(d.character(g).p.character.references[0].targetId,id);});

test('connected generation remaps repeated character blocks instead of reusing identities',async()=>{const {generateConnectedMap}=await import('../dist/tactics/editor-3d-generator.js');const d=doc(),id=place(d);edit(d,id,{scriptId:'resident',references:[{role:'self',targetId:id}]});const block=d.capture(0,0),empty=doc().capture(0,0),ports={north:'none',east:'none',south:'none',west:'none'};block.connections=ports;empty.connections=ports;const generated=generateConnectedMap([block,empty],7);assert.ok(generated.guards.length>1);assert.equal(new Set(generated.guards.map(p=>p.character.id)).size,generated.guards.length);assert.equal(new Set(generated.guards.map(p=>p.character.scriptId)).size,generated.guards.length);for(const p of generated.guards)assert.equal(p.character.references[0].targetId,p.character.id);});

test('block duplication rejects destinations outside the editable block without losing the source',()=>{const d=doc();place(d);const block=new EditingDocument().open(JSON.stringify(d.capture(0,0))),id=block.map.guards[0].character.id,before=block.export();assert.throws(()=>block.duplicateCharacter(id,{x:24,y:10,z:0}),/inside/);assert.equal(block.export(),before);});

test('combat behavior edits validate, undo and survive export',()=>{const d=doc(),id=place(d,10,'npc');assert.equal(d.character(id).p.character.combatBehavior,'cower');edit(d,id,{combatBehavior:'flee'});d.undo();assert.equal(d.character(id).p.character.combatBehavior,'cower');d.redo();assert.equal(new EditingDocument().open(d.export()).character(id).p.character.combatBehavior,'flee');assert.throws(()=>edit(d,id,{combatBehavior:'execute'}),/fight, cower or flee/);});
