import test from 'node:test';import assert from 'node:assert/strict';
import {RAMP_DIRECTIONS,rampInfo,rampHeight,rampRayHit,rampErrors} from '../dist/tactics/cliff-ramps.js';
import {blankMap,validateMap,neighbors} from '../dist/tactics/core/maps.js';
import {createGame,pathTo,move,stepMovement,refresh} from '../dist/tactics/core/engine.js';
import {unitBaseHeight} from '../dist/tactics/tower-geometry.js';
import {EditingDocument} from '../dist/tactics/editor-3d-controller.js';
const fixture=(direction='east',surface='road')=>{const m=blankMap('Ramp'),p={x:16,y:16,z:0,kind:'ramp-'+surface+'-'+direction},r=rampInfo(p);m.props=[p,{x:r.exit.x,y:r.exit.y,z:0,kind:'cliff-ledge',cliffMask:15}];m.upper[0][r.exit.x+','+r.exit.y]='floor';m.starts[0]=r.entry;return {m,p,r};};
test('all cardinal ramps support normal walking up and down with increasing physical height',()=>{for(const direction of Object.keys(RAMP_DIRECTIONS)){const {m,p,r}=fixture(direction);assert.deepEqual(validateMap(m,{connectivity:false}),[]);const s=createGame(1,m,false),u=s.units[0];refresh(s);let path=pathTo(s,u,r.exit.x,r.exit.y,1);assert.equal(path.length,5);assert.ok(path.every(q=>q.cost===2));assert.equal(move(s,u,r.exit.x,r.exit.y,1),true);let height=0;while(s.queue.length){stepMovement(s);assert.ok(unitBaseHeight(u)>=height);height=unitBaseHeight(u);}assert.equal(height,2);assert.equal(u.z,1);assert.equal(move(s,u,r.entry.x,r.entry.y,0),true);while(s.queue.length)stepMovement(s);assert.equal(unitBaseHeight(u),0);assert.equal(u.z,0);const side={x:r.low.x+r.dx,y:r.low.y+r.dy,z:0};assert.ok(neighbors(m,side).every(q=>r.dx?q.y===side.y:q.x===side.x));}});
test('ray intersections match the continuously sloped surface in all directions',()=>{for(const direction of Object.keys(RAMP_DIRECTIONS)){const {p,r}=fixture(direction);for(const t of [.2,1.3,2.7]){const q={x:r.low.x+r.dx*t,y:r.low.y+r.dy*t};const hit=rampRayHit([p],{...q,h:4},{x:0,y:0,h:-1},6);assert.ok(Math.abs((4-hit)-rampHeight(p,q))<1e-8);}}});
test('missing landings reject and editor persistence retains ramps',()=>{const {m,r}=fixture();const d=new EditingDocument().open(JSON.stringify(m));assert.equal(new EditingDocument().open(d.export()).map.props[0].kind,'ramp-road-east');delete m.upper[0][r.exit.x+','+r.exit.y];assert.ok(rampErrors(m).some(e=>e.includes('landing')));});

test('editor placement and removal are undoable and ramp links never use cliff AP',()=>{const {m,p}=fixture('south','grass');m.props=m.props.filter(q=>q!==p);const d=new EditingDocument().open(JSON.stringify(m));assert.ok(d.apply({tool:'prop',start:p,options:{propKind:p.kind,rotated:false}}).ok);const saved=d.export();d.undo();assert.ok(!d.map.props.some(q=>q.kind===p.kind));d.redo();assert.equal(d.export(),saved);const block=d.capture(0,0);assert.ok(block.props.some(q=>q.kind===p.kind));assert.ok(d.apply({tool:'erase-prop',start:p}).ok);d.undo();assert.equal(d.export(),saved);});
