import test from 'node:test';
import assert from 'node:assert/strict';
import {blankMap,setTerrain,neighbors,validateMap,parseMap,edgeKey} from '../dist/tactics/core/maps.js';
import {createEditor,applyBrush,beginStroke,endStroke,undo,redo} from '../dist/tactics/core/editor-model.js';
import {createGame,pathTo,pathCost,move,stepMovement,movementNeighbors,stepEnemy} from '../dist/tactics/core/engine.js';
import {nearbyCliffClimbs} from '../dist/tactics/cliff-actions.js';
import {captureEncounter,restoreEncounter} from '../dist/tactics/encounter-save.js';
import {startEncounterClock} from '../dist/tactics/encounter-clock.js';
function fixture(){const m=blankMap();setTerrain(m,4,4,1,'floor');m.climbs=[{x:3,y:4,z:0,dx:1,dy:0,kind:'cliff'}];return m;}
function game(){const s=createGame(1,fixture(),true,'easy'),u=s.units[0];s.phase='player';return {s,u};}
test('cliff links cost exactly 8 AP in both directions and every movement mode',()=>{
 for(const mode of [{},{running:true},{sneaking:true}]){const {s,u}=game();Object.assign(u,mode);assert.equal(pathCost(pathTo(s,u,4,4,1)),8);u.ap=7;assert.equal(move(s,u,4,4,1),false);assert.equal(nearbyCliffClimbs(s,u)[0].ok,false);u.ap=16;assert.equal(move(s,u,4,4,1),true);assert.equal(stepMovement(s),true);assert.deepEqual([u.x,u.y,u.z,u.ap],[4,4,1,8]);s.phase='player';assert.equal(move(s,u,3,4,0),true);assert.equal(stepMovement(s),true);assert.deepEqual([u.x,u.y,u.z,u.ap],[3,4,0,0]);assert.deepEqual(s.cliffTraversals.map(e=>e.direction),['up','down']);assert.equal(stepMovement(s),false);assert.equal(s.cliffTraversals.length,2);}
});
test('editor links roundtrip, protect endpoints and support erase undo',()=>{const e=createEditor(blankMap());setTerrain(e.map,4,4,1,'floor');beginStroke(e);assert.equal(applyBrush(e,'cliff',3,4,edgeKey('e',3,4)),'');endStroke(e);assert.equal(e.map.climbs[0].kind,'cliff');assert.deepEqual(validateMap(e.map),[]);assert.deepEqual(parseMap(JSON.stringify(e.map)).climbs,e.map.climbs);assert.ok(applyBrush(e,'water',3,4));beginStroke(e);applyBrush(e,'erase-roof',4,4,null,{level:1});endStroke(e);assert.equal(e.map.climbs.length,0);undo(e);assert.equal(e.map.climbs.length,1);redo(e);assert.equal(e.map.climbs.length,0);});
test('unsupported crag tags, water, headroom and blocked upper edges reject routes',()=>{for(const mutate of [m=>m.climbs[0].kind='crag',m=>setTerrain(m,3,4,0,'water'),m=>setTerrain(m,4,4,1,'void'),m=>setTerrain(m,3,4,1,'floor'),m=>m.edges[edgeKey('e',3,4,1)]='wall']){const m=fixture();mutate(m);assert.ok(validateMap(m).length);}});
test('cancellation, casualty, obstruction and AP changes do not commit climbs',()=>{for(const mutate of [(s,u)=>s.queue=[],(s,u)=>u.hp=0,(s,u)=>u.ap=7,(s,u)=>s.edges[edgeKey('e',3,4,1)]='wall',(s,u)=>Object.assign(s.units[1],{x:4,y:4,z:1})]){const {s,u}=game();u.ap=12;assert.ok(move(s,u,4,4,1));mutate(s,u);const ap=u.ap;assert.equal(stepMovement(s),false);assert.equal(u.z,0);assert.equal(u.ap,ap);assert.equal(s.cliffTraversals,undefined);}});
test('crouched actors cannot climb; legacy roofs still cost 6',()=>{const {s,u}=game();u.stance='kneeling';assert.equal(movementNeighbors(s,u).some(p=>p.kind==='cliff'),false);const m=fixture();delete m.climbs[0].kind;assert.equal(neighbors(m,{x:3,y:4,z:0}).find(p=>p.kind==='roof').cost,6);});
test('guard AI charges 8 and preserves traversal metadata',()=>{const m=fixture();setTerrain(m,5,4,1,'floor');m.starts[0]={x:5,y:4,z:1};m.guards=[{x:3,y:4,z:0,species:'donkey',weapon:'knife'}];const s=createGame(1,m,false,'easy'),g=s.units[4];for(const u of s.units.slice(1,4))u.hp=0;s.phase='enemy';s.enemyIndex=4;g.ap=8;g.alert=true;g.lastKnown={x:5,y:4,z:1};g.heading=0;assert.ok(stepEnemy(s));assert.deepEqual([g.x,g.y,g.z,g.ap],[4,4,1,0]);assert.equal(s.cliffTraversals[0].unitId,g.id);});
test('save/load retains the committed climb without replaying events',()=>{const {s,u}=game();startEncounterClock(s);u.ap=12;assert.ok(move(s,u,4,4,1));stepMovement(s);const loaded=restoreEncounter(captureEncounter(s));assert.equal(loaded.units[0].z,1);assert.equal(loaded.units[0].ap,4);assert.equal(loaded.climbs[0].kind,'cliff');assert.equal(loaded.cliffTraversals,undefined);assert.equal(loaded.cliffTraversalSequence,undefined);});

test('stamina is checked again at execution and equipment is preserved',()=>{const {s,u}=game();u.stats={strength:50};u.maxStamina=100;u.stamina=100;const equipment=structuredClone({weapon:u.weapon,slots:u.slots,pack:u.pack});assert.ok(move(s,u,4,4,1));u.stamina=0;assert.equal(stepMovement(s),false);assert.equal(u.z,0);assert.equal(s.cliffTraversals,undefined);u.stamina=100;assert.ok(move(s,u,4,4,1));assert.ok(stepMovement(s));assert.ok(u.stamina<100);assert.deepEqual({weapon:u.weapon,slots:u.slots,pack:u.pack},equipment);});
test('group execution emits a cliff event and charges the same 8 AP',()=>{const {s,u}=game();u.ap=12;s.queue=[{group:[{id:u.id,goal:{x:4,y:4,z:1}}]}];assert.ok(stepMovement(s));assert.equal(u.ap,4);assert.equal(u.z,1);assert.equal(s.cliffTraversals.length,1);assert.equal(s.cliffTraversals[0].unitId,u.id);});
test('exploration permits a low-AP merc to climb without charging combat AP',()=>{const {s,u}=game();s.phase='explore';u.ap=4;assert.ok(move(s,u,4,4,1));assert.ok(stepMovement(s));assert.equal(u.ap,4);assert.equal(u.z,1);});
