import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as T from '../dist/tactics/vendor/three.module.js';
import {ANIMAL_MOTION_CATALOG} from '../dist/tactics/animal-motion-catalog.js';
import {createWeaponModel} from '../dist/tactics/weapon-models.js';
import {BattleTraversal} from '../dist/tactics/battle-traversal.js';
import {cliffAnimationFrame} from '../dist/tactics/cliff-journey.js';
import {blankMap,setTerrain} from '../dist/tactics/core/maps.js';
import {createGame,move,stepMovement} from '../dist/tactics/core/engine.js';
import {toWorld} from '../dist/tactics/hybrid-world.js';
import {captureEncounter,restoreEncounter} from '../dist/tactics/encounter-save.js';
import {startEncounterClock} from '../dist/tactics/encounter-clock.js';
function fixture(dx=1,dy=0,species='horse',weapon='rifle'){
 const m=blankMap();m.starts[0]={x:8,y:8,z:0};m.climbs=[{x:8,y:8,z:0,dx,dy,kind:'cliff'}];for(const step of [1,2])for(const side of [-1,0,1]){const x=8+dx*step-dy*side,y=8+dy*step+dx*side;setTerrain(m,x,y,1,'floor');m.props.push({kind:'cliff-ledge',x,y,z:0});}
 const s=createGame(1,m,true,'easy'),u=s.units[0];Object.assign(u,{species,weapon,ap:12});s.phase='player';assert.ok(move(s,u,8+dx,8+dy,1));assert.ok(stepMovement(s));return {s,u,event:s.cliffTraversals[0]};
}
function model(species,weapon){const profile=ANIMAL_MOTION_CATALOG.find(p=>p.id===species),worker=profile.create(JSON.parse(fs.readFileSync(new URL('../dist/tactics/'+profile.file,import.meta.url)))),root=new T.Group();root.add(worker.root);let equipment;if(!profile.unarmed){equipment=createWeaponModel(weapon);worker.equipWeapon(equipment);}worker.pose('carry');return {worker,root,profile,dispose(){equipment?.dispose();worker.dispose();}};}
for(const profile of ANIMAL_MOTION_CATALOG)test(profile.id+' live cliff ascent consumes event once and restores the rig at exact landing',()=>{
 const weapon=profile.unarmed?'hands':'rifle',{s,u,event}=fixture(1,0,profile.id,weapon),m=model(profile.id,weapon),before=structuredClone(s),attrs=m.worker.parts.map(p=>p.geometry.attributes.position.array.slice()),v=new BattleTraversal(()=>{throw Error('Roof must not prepare ladders');});
 try{v.observe(s,0);assert.ok(v.busy);v.pose(m,u,0);assert.deepEqual(v.active.position,toWorld(event.from));assert.equal(u.ap,4);v.pose(m,u,3500);assert.ok(v.active.position.every(Number.isFinite));v.pose(m,u,8000);assert.ok(new T.Vector3(...v.active.position).distanceTo(new T.Vector3(...toWorld(u)))<1e-8);v.observe(s,8001);assert.equal(v.busy,false);v.observe(s,8000);assert.equal(v.busy,false);assert.deepEqual(s,before);m.worker.parts.forEach((p,i)=>assert.deepEqual(p.geometry.attributes.position.array,attrs[i]));}finally{v.finish();m.dispose();}
});
test('cliff frame and entry/exit align in all cardinal directions',()=>{for(const [dx,dy]of [[1,0],[0,1],[-1,0],[0,-1]]){const {s,u,event}=fixture(dx,dy),f=cliffAnimationFrame(s,event,u);assert.ok(f);assert.deepEqual(f.origin,[8+dx*.5,0,8+dy*.5]);}});
test('casualty, reduced motion, weapon change and cancellation preserve committed position/AP and restore equipment',()=>{for(const cancel of [(s,u,v)=>{u.hp=0;v.observe(s,1000);},(s,u,v)=>{u.weapon='pistol';v.observe(s,1000);},(s,u,v)=>v.observe(s,1000,true),(s,u,v)=>v.clear()]){const {s,u}=fixture(),m=model('horse','rifle'),v=new BattleTraversal(),attrs=m.worker.parts.map(p=>p.geometry.attributes.skinWeight.array.slice());try{v.observe(s,0);v.pose(m,u,0);v.pose(m,u,3000);cancel(s,u,v);assert.equal(v.busy,false);assert.deepEqual([u.x,u.y,u.z,u.ap],[9,8,1,4]);assert.ok(m.worker.weapon.root.visible);m.worker.parts.forEach((p,i)=>assert.deepEqual(p.geometry.attributes.skinWeight.array,attrs[i]));}finally{v.finish();m.dispose();}}});
test('unsupported loads, descent, occupied landing and parapets do not start mantle',()=>{const {s,u,event}=fixture();assert.equal(cliffAnimationFrame(s,{...event,direction:'down'},u),null);assert.equal(cliffAnimationFrame(s,event,{...u,weapon:'pistol'}),null);const occupied=structuredClone(s);Object.assign(occupied.units[1],event.to);assert.equal(cliffAnimationFrame(occupied,event,u),null);const parapet=structuredClone(s);parapet.props.push({...event.to,kind:'roof-climbable-flat-parapet'});assert.equal(cliffAnimationFrame(parapet,event,u),null);});
test('cliff events are transient across save/load and failed movement never records one',()=>{const {s,u}=fixture();startEncounterClock(s);const loaded=restoreEncounter(captureEncounter(s));assert.equal(loaded.cliffTraversals,undefined);assert.equal(loaded.cliffTraversalSequence,undefined);assert.equal(loaded.units[0].z,1);assert.equal(u.ap,4);s.phase='player';u.ap=0;assert.equal(move(s,u,8,8,0),false);assert.equal(s.cliffTraversals.length,1);});

test('mantle requires a supported clear cap behind the landing',()=>{const {s,u,event}=fixture();const shallow=structuredClone(s);shallow.props=shallow.props.filter(p=>p.x!==10);assert.equal(cliffAnimationFrame(shallow,event,u),null);const occupied=structuredClone(s);Object.assign(occupied.units[1],{x:10,y:8,z:1});assert.equal(cliffAnimationFrame(occupied,event,u),null);});

test('all species restore after casualty interruption, including the separate hen rig',()=>{for(const profile of ANIMAL_MOTION_CATALOG){const weapon=profile.unarmed?'hands':'rifle',{s,u}=fixture(1,0,profile.id,weapon),m=model(profile.id,weapon),v=new BattleTraversal(),attrs=m.worker.parts.map(p=>p.geometry.attributes.skinWeight.array.slice());try{v.observe(s,0);v.pose(m,u,0);v.pose(m,u,3500);u.hp=0;v.observe(s,3501);assert.equal(v.busy,false);assert.deepEqual([u.x,u.y,u.z,u.ap],[9,8,1,4]);m.worker.parts.forEach((p,i)=>assert.deepEqual(p.geometry.attributes.skinWeight.array,attrs[i]));}finally{v.finish();m.dispose();}}});
test('unarmed donkey guide uses the new cliff mantle',()=>{const {s,u}=fixture(1,0,'donkey','hands'),m=model('donkey','hands'),v=new BattleTraversal();try{v.observe(s,0);assert.ok(v.busy);v.pose(m,u,0);v.pose(m,u,3500);assert.equal(v.active.motion.climb.equipmentState,'carried');v.pose(m,u,8000);assert.deepEqual(v.active.position,toWorld(u));}finally{v.finish();m.dispose();}});
