import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as T from '../dist/tactics/vendor/three.module.js';
import {createLightHorse} from '../dist/tactics/horse-light-model.js';
import {BattleTraversal} from '../dist/tactics/battle-traversal.js';
import {cliffAnimationFrame,createCliffJourney} from '../dist/tactics/cliff-journey.js';
import {blankMap,setTerrain} from '../dist/tactics/core/maps.js';
import {createGame,move,stepMovement} from '../dist/tactics/core/engine.js';
import {toWorld,buildWorld} from '../dist/tactics/hybrid-world.js';
import {unitBaseHeight} from '../dist/tactics/tower-geometry.js';
function fixture(dx=1,dy=0){const m=blankMap();m.starts[0]={x:8,y:8,z:0};m.climbs=[{x:8,y:8,z:0,dx,dy,kind:'cliff'}];for(const side of [-1,0,1]){const x=8+dx-dy*side,y=8+dy+dx*side;m.props.push({kind:'cliff-ledge',x,y,z:0});setTerrain(m,x,y,1,'floor');}const s=createGame(1,m,true,'easy'),u=s.units[0];Object.assign(u,{species:'horse',weapon:'rifle',ap:12});s.phase='player';assert.ok(move(s,u,8+dx,8+dy,1));assert.ok(stepMovement(s));return {s,u,event:s.cliffTraversals[0]};}
const makeModel=()=>{const worker=createLightHorse(JSON.parse(fs.readFileSync(new URL('../dist/tactics/horse-10k-data.json',import.meta.url)))),root=new T.Group();root.add(worker.root);worker.pose('carry');return {worker,root,profile:{id:'horse'}};};
test('live cliff events animate once, restore equipment and end at exact supported tile in all headings',()=>{for(const [dx,dy]of [[1,0],[0,1],[-1,0],[0,-1]]){const {s,u,event}=fixture(dx,dy),frame=cliffAnimationFrame(s,event,u);assert.ok(frame);const model=makeModel(),before=structuredClone(s),v=new BattleTraversal(()=>{throw Error('Cliffs must not prepare ladder routes');});v.observe(s,0);assert.ok(v.busy);assert.ok(v.pose(model,u,0));assert.deepEqual(v.active.position,toWorld(event.from));v.pose(model,u,3500);assert.equal(v.active.motion.climb.equipmentState,'stowed');v.pose(model,u,6850);assert.ok(new T.Vector3(...v.active.position).distanceTo(new T.Vector3(...toWorld(u)))<1e-8);v.observe(s,6851);assert.equal(v.busy,false);v.observe(s,7000);assert.equal(v.busy,false);assert.deepEqual(s,before);assert.equal(unitBaseHeight(u),2);assert.equal(toWorld(u)[1],2);model.worker.dispose();}});
test('casualties, equipment changes, reduced motion and explicit cancellation restore rig without undoing gameplay',()=>{for(const cancel of [(s,u,v)=>{u.hp=0;v.observe(s,1000);},(s,u,v)=>{u.weapon='pistol';v.observe(s,1000);},(s,u,v)=>v.observe(s,1000,true),(s,u,v)=>v.clear()]){const {s,u}=fixture(),model=makeModel(),geometry=model.worker.parts.map(p=>p.geometry.attributes.skinWeight),v=new BattleTraversal();v.observe(s,0);v.pose(model,u,0);v.pose(model,u,3000);cancel(s,u,v);assert.equal(v.busy,false);assert.deepEqual([u.x,u.y,u.z,u.ap],[9,8,1,4]);assert.ok(model.worker.weapon.root.visible);model.worker.parts.forEach((p,i)=>assert.equal(p.geometry.attributes.skinWeight,geometry[i]));model.worker.dispose();}});
test('unsupported descent, species, weapon, crag, curved edge and occupied clearance safely fall back',()=>{const {s,u,event}=fixture();for(const changed of [{...event,direction:'down'}])assert.equal(cliffAnimationFrame(s,changed,u),null);for(const change of [{species:'hen'},{weapon:'pistol'}])assert.equal(cliffAnimationFrame(s,event,{...u,...change}),null);for(const change of [{kind:'cliff-crag'},{cliffMask:3}]){const copy=structuredClone(s);Object.assign(copy.props[0],change);assert.equal(cliffAnimationFrame(copy,event,u),null);}const copy=structuredClone(s);Object.assign(copy.units[1],{x:9,y:9,z:1});assert.equal(cliffAnimationFrame(copy,event,u),null);});

test('cliff caps replace upper rendering slabs and phantom projectile floors',async()=>{const {s,u}=fixture();const {traceProjectile}=await import('../dist/tactics/core/projectiles.js');assert.equal(buildWorld({...s,terrain:s.map}).boxes.some(b=>b.id==='floor:9,8,1'),false);const clear={...s,units:[]};const ray=traceProjectile(clear,null,{x:9,y:8,h:2.7},{x:0,y:0,h:1},.6);assert.equal(ray.kind,'range');const rock=traceProjectile(clear,null,{x:9,y:8,h:2.7},{x:0,y:0,h:-1},1);assert.equal(rock.kind,'cover');assert.ok(Math.abs(rock.h-2)<1e-6);});
