import test from 'node:test';import assert from 'node:assert/strict';
import {blankMap,validateMap,parseMap} from '../dist/tactics/core/maps.js';
import {createEditor,applyBrush} from '../dist/tactics/core/editor-model.js';
import {createGame} from '../dist/tactics/core/engine.js';
import {TOWN_GUIDE_APPEARANCE} from '../dist/tactics/donkey-hawaiian.js';
test('guide outfit survives placement, map roundtrip and runtime character creation',()=>{const e=createEditor(blankMap());assert.equal(applyBrush(e,'guard',10,10,null,TOWN_GUIDE_APPEARANCE),'');assert.deepEqual(validateMap(e.map),[]);const m=parseMap(JSON.stringify(e.map));assert.equal(m.guards[0].outfit,'blue-hawaiian');const s=createGame(1,m,false);assert.equal(s.units[4].outfit,'blue-hawaiian');assert.equal(s.units[4].weapon,'hands');assert.equal(s.units[4].species,'donkey');assert.equal(applyBrush(e,'guard',10,10,null,{species:'donkey',weapon:'hands',outfit:'normal'}),'');assert.equal(e.map.guards[0].outfit,undefined);});
test('Hawaiian appearance is limited to donkeys and existing uniforms remain valid',()=>{const m=blankMap();m.guards=[{x:10,y:10,...TOWN_GUIDE_APPEARANCE}];m.guards[0].species='horse';assert.ok(validateMap(m).length);m.guards[0].outfit='red-hats';assert.deepEqual(validateMap(m),[]);});

test('straw hat has actual ear openings, follows head motion and disposes cleanly',async()=>{const fs=await import('node:fs'),T=await import('../dist/tactics/vendor/three.module.js'),{createDonkeyWorker}=await import('../dist/tactics/donkey-worker.js'),{createDonkeyStrawHat}=await import('../dist/tactics/donkey-straw-hat.js');const w=createDonkeyWorker(JSON.parse(fs.readFileSync(new URL('../dist/tactics/donkey-10k-data.json',import.meta.url)))),hat=createDonkeyStrawHat(w),head=w.bones.find(b=>b.name==='head');w.root.updateMatrixWorld(true);const hit=(x,z)=>new T.Raycaster(new T.Vector3(x,2,z),new T.Vector3(0,-1,0),0,1).intersectObject(hat.root,true);assert.equal(hit(-.063,-.078).length,0);assert.equal(hit(-.063,.078).length,0);assert.ok(hit(.025,0).length);assert.equal(hat.root.parent,head);const before=hat.root.matrixWorld.clone();head.rotation.y=.4;w.root.updateMatrixWorld(true);assert.notDeepEqual(hat.root.matrixWorld.elements,before.elements);hat.dispose();hat.dispose();assert.equal(head.getObjectByName('Town guide straw hat'),undefined);w.dispose();});
