import test from 'node:test';import assert from 'node:assert/strict';
import {EditingDocument} from '../dist/tactics/editor-3d-controller.js';import {blankMap,validateMap,passable,neighbors} from '../dist/tactics/core/maps.js';import {createGame} from '../dist/tactics/core/engine.js';import {buildWorld} from '../dist/tactics/hybrid-world.js';import {canopyErrors} from '../dist/tactics/editor-canopies.js';import {STRUCTURE_PRESETS} from '../dist/tactics/editor-structure-presets.js';
const doc=()=>new EditingDocument().open(JSON.stringify(blankMap('Workbench')));
test('builder roof layer round trips, undoes, renders and never creates a playable floor',()=>{const d=doc();assert(d.apply({tool:'roof-tile',start:{x:10,y:10,z:3},options:{propKind:'roof-corrugated-flat'}}).ok);assert.equal(d.map.canopies.length,1);assert.equal(d.map.upper.length,2);assert.equal(passable(d.map,{x:10,y:10,z:3}),false);assert(neighbors(d.map,{x:10,y:10,z:2}).every(p=>p.z!==3));assert(buildWorld(d.map).boxes.some(b=>b.kind==='roof'&&b.source.z===3));const saved=d.export();d.undo();assert.equal(d.map.canopies?.length||0,0);d.redo();assert.equal(d.export(),saved);const copy=new EditingDocument().open(saved);assert.equal(copy.inspect(10,10,3).type,'prop');assert(copy.rotate(copy.inspect(10,10,3)).ok);assert(copy.map.canopies[0].rotated);const s=createGame(1,copy.map,false);assert.equal(s.canopies.length,1);assert.equal(s.upper.length,2);});
test('roof layer rejects units, ordinary objects, overlaps and out-of-bounds footprints atomically',()=>{const d=doc();for(const tool of ['squad','guard','floor','room','ladder'])assert.equal(d.apply({tool,start:{x:10,y:10,z:3}}).ok,false);assert(d.apply({tool:'roof-tile',start:{x:10,y:10,z:3},options:{propKind:'roof-flat-parapet'}}).ok);const before=d.export();assert.equal(d.apply({tool:'roof-tile',start:{x:11,y:11,z:3},options:{propKind:'roof-flat-parapet'}}).ok,false);assert.equal(d.export(),before);assert(canopyErrors({canopies:[{x:239,y:10,z:3,kind:'roof-flat-parapet'}]}).length);assert(d.apply({tool:'erase-prop',start:{x:10,y:10,z:3}}).ok);assert.equal(d.map.canopies.length,0);});
test('block capture and replacement translate decorative roofs without accumulating duplicates',()=>{const d=doc();d.apply({tool:'roof-tile',start:{x:10,y:10,z:3},options:{propKind:'roof-corrugated-flat'}});const block=d.capture(0,0),other=doc();other.place(block,1,1);other.place(block,1,1);assert.deepEqual(other.map.canopies,[{x:34,y:34,z:3,kind:'roof-corrugated-flat',rotated:false}]);const reopened=new EditingDocument().open(JSON.stringify(block));assert.equal(reopened.map.canopies[0].x,10);assert.deepEqual(validateMap(other.map),[]);});
test('preset structures stamp furniture and rotated footprints as one undoable edit',()=>{for(const preset of Object.keys(STRUCTURE_PRESETS).filter(p=>p!=='room'))for(const rotated of [false,true]){const d=doc(),r=d.apply({tool:'prefab',start:{x:30,y:30,z:0},options:{preset,rotated}});assert(r.ok,r.error);assert.equal(d.map.props.length,STRUCTURE_PRESETS[preset].objects.length);const serialized=d.export();d.undo();assert.equal(d.map.props.length,0);d.redo();assert.equal(d.export(),serialized);}});
test('rotate selected objects preserves metadata; directional terrain changes corner',()=>{const d=doc();assert(d.apply({tool:'prop',start:{x:20,y:20,z:0},options:{propKind:'table-wood'}}).ok);d.map.props[0].note='keep';assert(d.rotate(d.inspect(20,20,0,{mode:'prop'})).ok);assert(d.map.props[0].rotated);assert.equal(d.map.props[0].note,'keep');d.apply({tool:'texture',start:{x:30,y:30,z:0},options:{groundKind:'road-diagonal-grass-nw'}});assert(d.rotate(d.inspect(30,30,0,{mode:'tile'})).ok);assert.equal(d.map.terrain[30][30],'road-diagonal-grass-ne');});
test('rotating a boundary keeps its door lock',()=>{const d=doc();d.apply({tool:'wall',start:{x:20,y:20,z:0,edge:'e:20:20'},options:{edgeKind:'door-steel-closed'}});d.doorLock(d.inspect(20.49,20,0,{mode:'edge'}),70);assert(d.rotate(d.inspect(20.49,20,0,{mode:'edge'})).ok);assert.equal(d.map.edges['s:20:20'],'door-steel-closed');assert.equal(d.map.edgeLocks['s:20:20'],70);assert.equal(d.map.edges['e:20:20'],undefined);});
