import test from 'node:test';
import assert from 'node:assert/strict';
import {EditingDocument} from '../dist/tactics/editor-3d-controller.js';
import {blankMap,validateMap,neighbors} from '../dist/tactics/core/maps.js';
import {RAMP_DIRECTIONS,rampInfo,rampMoveAllowed} from '../dist/tactics/cliff-ramps.js';
function setup(direction){const d=new EditingDocument().open(JSON.stringify(blankMap('Ramp stroke'))),[dx,dy]=RAMP_DIRECTIONS[direction];for(let i=0;i<4;i++)assert(d.apply({tool:'cliff',start:{x:30+(dx?0:i),y:30+(dx?i:0),z:0}}).ok);const edge=dx?`e:${30-(dx>0?1:0)}:30`:`s:30:${30-(dy>0?1:0)}`;return {d,start:{x:30,y:30,z:0,edge},end:{x:30+(dx?0:2),y:30+(dx?2:0),z:0}};}
for(const direction of Object.keys(RAMP_DIRECTIONS))test(`wall drag builds a three-wide ${direction} ramp as one edit`,()=>{const {d,start,end}=setup(direction),before=d.export(),command={tool:'ramp',start,end,options:{rampSurface:'road'}},preview=d.preview(command);assert(preview.ok,preview.error);assert.equal(d.export(),before);assert.equal(preview.cells.length,12);assert(d.apply(command).ok);const ramps=d.map.props.filter(p=>p.kind.startsWith('ramp-'));assert.equal(ramps.length,3);for(const p of ramps){assert.equal(p.kind,`ramp-road-${direction}`);const r=rampInfo(p);assert.equal(d.map.upper[0][`${r.exit.x},${r.exit.y}`],'floor');}assert(rampMoveAllowed(d.map,rampInfo(ramps[0]).low,rampInfo(ramps[1]).low));const a=rampInfo(ramps[0]).low,b=rampInfo(ramps[1]).low;assert(neighbors(d.map,a).some(q=>q.x===b.x&&q.y===b.y&&q.z===b.z));assert.deepEqual(validateMap(d.map,{connectivity:false}),[]);const after=d.export();d.undo();assert.equal(d.export(),before);d.redo();assert.equal(d.export(),after);assert.equal(new EditingDocument().open(after).map.props.length,d.map.props.length);});
test('wall drag rejects gaps and occupied lanes without partial ramps or floors',()=>{const {d,start,end}=setup('east');assert(d.apply({tool:'prop',start:{x:27,y:31,z:0},options:{propKind:'barrel-single'}}).ok);const before=d.export(),r=d.apply({tool:'ramp',start,end});assert.equal(r.ok,false);assert.equal(d.export(),before);const clean=setup('north');assert.equal(clean.d.apply({tool:'ramp',start:clean.start,end:{x:35,y:30,z:0}}).ok,false);assert.equal(clean.d.map.props.filter(p=>p.kind.startsWith('ramp-')).length,0);});
test('reverse drag uses the same lanes; bare terrain and clipped ledges are rejected',()=>{const {d,start,end}=setup('west'),forward=d.preview({tool:'ramp',start,end}),back=d.preview({tool:'ramp',start:{...end,edge:'e:30:32'},end:start});assert(back.ok,back.error);assert.deepEqual(back.map,forward.map);assert.equal(d.preview({tool:'ramp',start:{x:10,y:10,z:0}}).ok,false);d.map.props[0].cliffMask=3;assert.equal(d.preview({tool:'ramp',start,end}).ok,false);});
test('sideways ramp movement requires an adjacent lane at the same height',()=>{const map={props:[{kind:'ramp-road-east',x:10,y:10,z:0},{kind:'ramp-road-east',x:11,y:11,z:0}]};assert.equal(rampMoveAllowed(map,{x:11,y:10,z:0},{x:11,y:11,z:0}),false);assert.equal(rampMoveAllowed(map,{x:11,y:10,z:0},{x:11,y:9,z:0}),false);});
