import test from 'node:test';import assert from 'node:assert/strict';import {helicoidShot,seededShots,studyBody,traceStudy} from '../dist/tactics/helicoid-shot.js';
const base={origin:[0,0,1.3],aim:[0,20,1.12],accuracy:60,precision:80,roll:.5,rotation:.25};
test('seeded inputs reproduce trajectories, center roll follows aim, vertical axes remain finite',()=>{const a=seededShots(42),b=seededShots(42);for(let i=0;i<100;i++)assert.equal(a(),b());assert.ok(helicoidShot({...base,roll:0}).targetPlane.every((v,i)=>Math.abs(v-base.aim[i])<1e-10));for(const aim of [[0,0,20],[0,0,-20],[20,0,1.3]])assert.ok(helicoidShot({...base,aim}).direction.every(Number.isFinite));assert.throws(()=>helicoidShot({...base,aim:base.origin}));});
test('distance depth is bounded and spread tightens with accuracy and precision',()=>{const near=helicoidShot({...base,aim:[0,1,1.3]}),far=helicoidShot({...base,aim:[0,10000,1.3]});assert.equal(near.depth,1.08);assert.equal(far.depth,.92);assert.ok(helicoidShot({...base,accuracy:100}).radius<helicoidShot(base).radius);assert.ok(helicoidShot({...base,precision:100}).radius<helicoidShot(base).radius);});
test('torso-aimed trajectories can strike legs, and cover intercepts before body',()=>{const random=seededShots(42),hits=new Set();for(let i=0;i<3000;i++){const shot=helicoidShot({...base,accuracy:40,roll:random(),rotation:random()});hits.add(traceStudy(shot,studyBody).zone);}assert.ok(hits.has('legs'));assert.ok(hits.has('head'));assert.ok(hits.has('torso'));assert.ok(hits.has('miss'));const center=helicoidShot({...base,roll:0});assert.equal(traceStudy(center,studyBody).zone,'torso');assert.equal(traceStudy(center,studyBody,true).zone,'cover');});

test('one-metre shots can miss even at maximum accuracy, and better aim remains more reliable',()=>{
 const bodies=studyBody.map(b=>({...b,center:[b.center[0],1,b.center[2]]}));
 const hits=accuracy=>{const r=seededShots(42);let n=0;for(let i=0;i<10000;i++){const shot=helicoidShot({...base,aim:[0,1,1.12],accuracy,roll:r(),rotation:r()});if(['head','torso','legs'].includes(traceStudy(shot,bodies).zone))n++;}return n;};
 const low=hits(1),normal=hits(65),high=hits(100);assert.ok(low<normal&&normal<high);assert.ok(high<10000);assert.ok(normal>8000&&normal<9800);
});
