import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from '../dist/tactics/vendor/three.module.js';
import {ANIMAL_MOTION_CATALOG as profiles} from '../dist/tactics/animal-motion-catalog.js';import {createHenMotion} from '../dist/tactics/hen-motion.js';import {createHenLadderMotion} from '../dist/tactics/hen-ladder-motion.js';import {createHenLadderJourney} from '../dist/tactics/hen-ladder-journey.js';import {createLadderJourney} from '../dist/tactics/ladder-journey.js';import {LADDER_PRESETS} from '../dist/tactics/ladder-motion.js';import {ladderFrame} from '../dist/tactics/battle-traversal.js';import {towerEntry,towerSlots,towerPost,towerCenter} from '../dist/tactics/tower-geometry.js';import {createFurnitureLibrary} from '../dist/tactics/painted-furniture.js';import {toWorld} from '../dist/tactics/hybrid-world.js';
const profile=profiles.find(p=>p.id==='hen'),load=()=>profile.create(JSON.parse(fs.readFileSync(new URL('../dist/tactics/'+profile.file,import.meta.url)))),V=a=>new T.Vector3(...a),snapshot=w=>({attributes:w.parts.map(p=>Object.fromEntries(Object.entries(p.geometry.attributes).map(([k,a])=>[k,a.array.slice()]))),skeleton:w.parts[0].skeleton,bones:w.parts[0].skeleton.bones.map(b=>({b,parent:b.parent,p:b.position.clone()})),nodes:[]});
function restored(w,s){w.parts.forEach((p,i)=>{assert.equal(p.skeleton,s.skeleton);for(const[k,a]of Object.entries(s.attributes[i]))assert.deepEqual(p.geometry.attributes[k].array,a,k+' not restored');});s.bones.forEach(({b,parent,p})=>{assert.equal(b.parent,parent);assert.ok(b.position.distanceTo(p)<1e-8);});assert.equal(w.root.getObjectByName('wing brace -1'),undefined);}
for(const kind of ['wooden-spotlight-tower','iron-searchlight-ladder-tower'])test('hen '+kind+': visible contacts, explicit flight, landing, fixed anatomy and reversible ownership',()=>{
 const w=load(),s=snapshot(w),texture=new T.Texture(),library=createFurnitureLibrary(texture,texture);try{for(const direction of['up','down'])for(const rotated of[false,true])for(const slot of[0,3]){
 const tower={kind,x:4,y:5,z:1,rotated},bottom=towerEntry(tower),top=towerSlots(tower)[slot];top.towerPost=towerPost(tower,top);const event={tower,direction,from:direction==='up'?bottom:top,to:direction==='up'?top:bottom},frame=ladderFrame(tower),m=createLadderJourney(w,profile,event,frame,37),lengths=new Map(m.climb.skeleton.bones.map(b=>[b,b.position.length()]));
 try{assert.equal(m.climb.duration,6);assert.equal(w.weapon,undefined);for(const progress of[0,1]){const r=m.apply(progress);assert.ok(V(r.root).distanceTo(V(toWorld(progress?event.to:event.from)))<1e-8);assert.equal(r.airborne,false);}
 let flights=0;for(const phase of m.phases)for(let i=0;i<=60;i++){const p=(phase.start+(phase.end-phase.start)*i/60)/m.duration,r=m.apply(p);for(const c of r.contacts)assert.ok(c.error<1e-5);for(const[b,len]of lengths)assert.ok(Math.abs(b.position.length()-len)<1e-8,'limb length changed');if(r.airborne){flights++;assert.ok(r.contacts.every(c=>c.kind==='airborne'&&!c.planted));}
 if(phase.label==='Climb'&&!r.airborne){for(const c of r.contacts.filter(c=>c.planted&&c.kind==='brace')){const l=m.climb.limbs.find(l=>l.id===c.id),point=l.surface.getVertexPosition(l.index,new T.Vector3()).applyMatrix4(l.surface.matrixWorld);assert.ok(point.distanceTo(V(c.worldPoint))<1e-5,'feather surface misses brace');}for(const c of r.contacts.filter(c=>c.planted&&c.kind==='rung')){const l=m.climb.limbs.find(l=>l.id===c.id);let nearest=Infinity;for(const j of new Set(l.surface.geometry.index.array)){const point=l.surface.getVertexPosition(j,new T.Vector3()).applyMatrix4(l.surface.matrixWorld);nearest=Math.min(nearest,point.distanceTo(V(c.worldPoint)));}assert.ok(nearest<.013,'toe surface misses rung: '+nearest);}}
 }
 assert.ok(flights>0,'assisted hop is not exposed');
 // Shared boundaries must not create a pose snap or a false flight contact.
 const base=m.phases.find(p=>p.label==='Climb').start;for(const ph of m.climb.phases.slice(-4)){const p=direction==='up'?ph.start:6-ph.start,rows=[];for(const epsilon of[-1e-7,0,1e-7]){m.apply((base+p+epsilon)/m.duration);rows.push(m.climb.skeleton.bones.map(b=>b.getWorldPosition(new T.Vector3())));}for(let i=0;i<rows[0].length;i++)assert.ok(rows[0][i].distanceTo(rows[2][i])<1e-4,'phase-boundary snap');}
 const samples=[.12,.44,.63,.88].map(t=>{m.apply(t);return{t,points:m.climb.skeleton.bones.map(b=>b.getWorldPosition(new T.Vector3()))};});for(const row of samples.reverse()){m.apply(row.t);m.climb.skeleton.bones.forEach((b,i)=>assert.ok(b.getWorldPosition(new T.Vector3()).distanceTo(row.points[i])<1e-8));}
 // Sample the real visible fixture and every visible actor surface, not contact markers.
 if(slot===0){const fixture=library.build(kind).root,c=towerCenter(tower);fixture.position.set(c.x,2.12,c.y);fixture.rotation.y=rotated?-Math.PI/2:0;fixture.updateMatrixWorld(true);const boxes=[];fixture.traverse(o=>{if(o.isMesh){o.geometry.computeBoundingBox();boxes.push({name:o.name,box:o.geometry.boundingBox,inv:o.matrixWorld.clone().invert(),world:new T.Box3().setFromObject(o)});}});for(const phase of m.phases)for(let i=0;i<=100;i++){m.apply((phase.start+(phase.end-phase.start)*i/100)/m.duration);w.root.traverseVisible(mesh=>{if(!mesh.isMesh)return;const points=[...new Set(mesh.geometry.index?.array||[])].map(j=>mesh.getVertexPosition(j,new T.Vector3()).applyMatrix4(mesh.matrixWorld)),bounds=new T.Box3().setFromPoints(points),near=boxes.filter(b=>b.world.intersectsBox(bounds));for(const point of points)for(const o of near){if(!o.world.containsPoint(point))continue;const v=point.clone().applyMatrix4(o.inv),b=o.box;if(!b.containsPoint(v))continue;const depth=Math.min(v.x-b.min.x,b.max.x-v.x,v.y-b.min.y,b.max.y-v.y,v.z-b.min.z,b.max.z-v.z);assert.ok(depth<.005,mesh.name+' / '+o.name+' '+depth+' '+phase.label);}});}}
 }finally{m.dispose();m.dispose();restored(w,s);}
 }}finally{library.dispose();texture.dispose();w.dispose();}
});
test('hen ladder borrows an existing leg rig and rolls back failed constructors',()=>{
 const w=load();try{const owner=createHenMotion(w),s=snapshot(w);const m=createHenLadderMotion(w,{...LADDER_PRESETS.tower,exitWidth:.94});m.apply(.4);m.dispose();restored(w,s);assert.equal(w.parts[0].skeleton,owner.skeleton);owner.apply(0);owner.restore();
 for(const d of[{...LADDER_PRESETS.tower,plane:NaN},{...LADDER_PRESETS.tower,plane:2}]){w.root.position.set(3,2,1);w.root.rotation.y=.7;const p=w.root.position.clone(),q=w.root.quaternion.clone(),before=snapshot(w);assert.throws(()=>createHenLadderMotion(w,d));restored(w,before);assert.ok(w.root.position.distanceTo(p)<1e-8);assert.ok(w.root.quaternion.angleTo(q)<1e-8);}
 const tower={kind:'iron-searchlight-ladder-tower',x:0,y:0},event={tower,direction:'up',from:towerEntry(tower),to:towerSlots(tower)[0]},before=snapshot(w);assert.throws(()=>createHenLadderJourney(w,event,ladderFrame(tower),0,()=>{throw Error('Route failed');}),/Route failed/);restored(w,before);owner.dispose();assert.equal(w.root.getObjectByName('thigh -1'),undefined);
 }finally{w.dispose();}
});
