import test from 'node:test';import assert from 'node:assert/strict';
import {blank,route} from '../dist/tactics/overmap-model.js';
import {createGroups,orderGroup,splitGroup} from '../dist/tactics/overmap-groups.js';
import {ensureLogistics,advanceLogistics,resolveLogisticsEncounter,startMilitiaTraining,cancelMilitiaTraining,validateLogistics,WEEK} from '../dist/tactics/overmap-logistics.js';
function setup(){const map=blank();for(let i=0;i<30;i++)map.sectors[i].routes=[route('road','west','east')];Object.assign(map.sectors[1],{facilities:['factory'],owner:'red-hats'});Object.assign(map.sectors[4],{role:'fortress',owner:'red-hats'});Object.assign(map.sectors[20],{role:'town',owner:'player'});const s=createGroups(map);s.groups[0].state.position=20;const l=ensureLogistics(s,map);return {map,s,l,fort:l.forts[0]};}
test('arrival consumes weapons and starts exactly seven days, never the factory dispatch date',()=>{const {map,s,l,fort}=setup(),start=s.clock.minutes;advanceLogistics(s,map,179);assert.equal(fort.readyAt,null);assert.equal(l.convoys.length,1);advanceLogistics(s,map,1);assert.equal(fort.readyAt,start+180+WEEK);assert.equal(fort.stock,0);advanceLogistics(s,map,WEEK-1);assert.equal(l.raiders.length,0);advanceLogistics(s,map,1);assert.equal(l.raiders.length,1);assert.equal(l.raiders[0].target,20);assert.ok(l.raiders[0].state.route.length);});
test('interception pauses before delivery, requires troops and preserves the undelivered timer',()=>{const {map,s,l,fort}=setup();s.groups[0].state.position=2;const elapsed=advanceLogistics(s,map,180);assert.equal(elapsed,60);assert.equal(l.pending.kind,'convoy');assert.equal(fort.readyAt,null);assert.throws(()=>advanceLogistics(s,map,1));resolveLogisticsEncounter(s,'player-victory');assert.equal(l.weapons,1);assert.equal(l.convoys.length,0);assert.equal(fort.readyAt,null);});
test('clearing fortress stops recruitment, destroys queued stock, and cancels inbound deliveries',()=>{const {map,s,l,fort}=setup();advanceLogistics(s,map,180);assert.ok(fort.readyAt);s.groups[0].state.position=4;advanceLogistics(s,map,1);assert.equal(l.pending.kind,'fortress');resolveLogisticsEncounter(s,'player-victory');assert.equal(fort.owner,'player');assert.equal(fort.readyAt,null);advanceLogistics(s,map,WEEK);assert.equal(l.raiders.length,0);assert.equal(l.convoys.length,0);assert.equal(fort.stock,0);});
test('one batch at a time; stored weapons start the following week without retroactive spawning',()=>{const {map,s,l,fort}=setup();fort.stock=2;fort.nextDispatch=s.clock.minutes+3*WEEK;advanceLogistics(s,map,WEEK);assert.equal(l.raiders.length,1);assert.equal(fort.stock,0);assert.equal(fort.readyAt,s.clock.minutes+WEEK);});
test('nearest reachable merc target changes at sector boundaries; no target means waiting',()=>{const {map,s,l,fort}=setup();fort.stock=1;advanceLogistics(s,map,WEEK);const r=l.raiders[0];assert.equal(r.target,20);s.groups[0].state.position=8;advanceLogistics(s,map,1);assert.equal(r.target,8);assert.ok(r.state.progress>0);});
test('$500 militia assignment occupies group, uses leadership and completes only after elapsed training',()=>{const {map,s,l}=setup(),g=s.groups[0];startMilitiaTraining(s,map,g.id);assert.equal(l.money,4500);const duration=g.training.endsAt-s.clock.minutes;assert.equal(duration,3600);assert.throws(()=>orderGroup(s,map,g.id,19));assert.throws(()=>splitGroup(s,g.id,[0]));assert.throws(()=>startMilitiaTraining(s,map,g.id));advanceLogistics(s,map,duration-1);assert.equal(l.militia[20],undefined);advanceLogistics(s,map,1);assert.deepEqual(l.militia[20],{basic:4,medium:0,high:0,rounds:1});assert.equal(g.training,undefined);startMilitiaTraining(s,map,g.id);cancelMilitiaTraining(s,g.id);assert.equal(l.money,4000);assert.equal(g.training,undefined);l.money=499;assert.throws(()=>startMilitiaTraining(s,map,g.id));});
test('large skip equals minute ticks; saved clock, timers, convoys and training round trip',()=>{const {map,s}=setup(),other=structuredClone(s);startMilitiaTraining(s,map,s.groups[0].id);startMilitiaTraining(other,map,other.groups[0].id);advanceLogistics(s,map,1000);for(let i=0;i<1000;i++)advanceLogistics(other,map,1);assert.deepEqual(s,other);const saved=JSON.parse(JSON.stringify(s));validateLogistics(saved,map);assert.equal(saved.logistics.forts[0].readyAt,s.logistics.forts[0].readyAt);assert.ok(saved.groups[0].training);});

test('no connected enemy factory means no shipments or recruitment; unreachable mercs leave squads waiting',()=>{const {map,s,l,fort}=setup();map.sectors[1].owner='player';advanceLogistics(s,map,WEEK);assert.equal(l.convoys.length,0);assert.equal(fort.readyAt,null);fort.stock=1;map.sectors[20].role='tutorial';map.sectors[20].travel=[];advanceLogistics(s,map,WEEK);assert.equal(l.raiders.length,1);assert.equal(l.raiders[0].target,null);assert.equal(l.raiders[0].state.position,4);});
test('mercenaries at an enemy fortress pause time before its inbound convoy can deliver',()=>{const {map,s,l,fort}=setup();advanceLogistics(s,map,179);s.groups[0].state.position=4;advanceLogistics(s,map,1);assert.equal(l.pending.kind,'fortress');assert.equal(fort.readyAt,null);});
