import test from 'node:test';import assert from 'node:assert/strict';
import {blank,route} from '../dist/tactics/overmap-model.js';
import {createTravel} from '../dist/tactics/overmap-travel.js';
import {createGroups,splitGroup,orderGroup,destinationPreview,advanceGroups,arrival,validateGroups} from '../dist/tactics/overmap-groups.js';
function setup(){const map=blank();for(let x=0;x<30;x++)map.sectors[x].routes=[route('road','west','east')];const s=createGroups(map);const b=splitGroup(s,'group-1',[1]);return {map,s,a:s.groups[0],b};}
test('groups contain unique people, selection is explicit, split is atomic',()=>{const map=blank(),s=createGroups(map);assert.equal(s.selectedId,null);const before=structuredClone(s);assert.throws(()=>splitGroup(s,'group-1',[]));assert.deepEqual(s,before);assert.throws(()=>splitGroup(s,'group-1',[0,1,2,3]));const b=splitGroup(s,'group-1',[1,3]);assert.deepEqual(b.state.members.map(u=>u.name),['Anya','Vera']);assert.equal(s.groups[0].state.members.length,2);assert.equal(s.selectedId,b.id);assert.equal(b.state.position,s.groups[0].state.position);});
test('destination click preview does not commit orders or time; independent groups have separate ETAs',()=>{const {map,s,a,b}=setup(),before=structuredClone(s);const preview=destinationPreview(s,map,a.id,5);assert.ok(preview.preview.travelMinutes>0);assert.deepEqual(s,before);orderGroup(s,map,a.id,5);orderGroup(s,map,b.id,5);assert.notEqual(arrival(s,a),arrival(s,b));assert.equal(s.clock.minutes,480);assert.throws(()=>splitGroup(s,a.id,[0]));});
test('synchronize faster second group by holding it; both physically arrive together',()=>{const {map,s,a,b}=setup();orderGroup(s,map,a.id,8);const preview=destinationPreview(s,map,b.id,8);assert.equal(preview.others[0].id,a.id);assert.ok(preview.sharedArrival>preview.ownArrival);orderGroup(s,map,b.id,8,true);const end=arrival(s,a);assert.equal(arrival(s,b),end);advanceGroups(s,end-s.clock.minutes-1);assert.ok(a.state.route.length);assert.ok(b.state.route.length);advanceGroups(s,1);assert.equal(a.state.position,8);assert.equal(b.state.position,8);assert.equal(a.state.route.length,0);assert.equal(b.state.route.length,0);});
test('slower incoming order can synchronize a group already travelling, preserving its partial progress',()=>{const {map,s,a,b}=setup();orderGroup(s,map,b.id,8);advanceGroups(s,20);const progress=b.state.progress;orderGroup(s,map,a.id,8,true);assert.ok(b.waitMinutes>0);assert.equal(b.state.progress,progress);const end=arrival(s,a);assert.equal(arrival(s,b),end);advanceGroups(s,end-s.clock.minutes);assert.equal(a.state.position,8);assert.equal(b.state.position,8);});
test('global time advances each group once; fatigue and automatic required rest match ETA',()=>{const {map,s,a,b}=setup();orderGroup(s,map,a.id,20);orderGroup(s,map,b.id,20);const end=arrival(s,a);advanceGroups(s,480);assert.equal(s.clock.minutes,960);assert.equal(a.state.restRequired,true);assert.equal(Math.max(...a.state.members.map(u=>u.social.fatigue)),80);advanceGroups(s,120);assert.equal(Math.max(...a.state.members.map(u=>u.social.fatigue)),60);assert.equal(a.state.restRequired,false);advanceGroups(s,end-s.clock.minutes);assert.equal(a.state.position,20);assert.equal(a.state.route.length,0);assert.equal(b.state.position,20);assert.equal(a.state.clock.minutes,s.clock.minutes);assert.equal(b.state.clock.minutes,s.clock.minutes);});
test('scheduled groups save/reload, migrate old session, and reject duplicate people or mismatched clocks',()=>{const {map,s,a,b}=setup();orderGroup(s,map,a.id,8);orderGroup(s,map,b.id,8,true);advanceGroups(s,45);const restored=validateGroups(JSON.parse(JSON.stringify(s)),map);assert.deepEqual(restored,s);const end=arrival(s,a);advanceGroups(restored,end-restored.clock.minutes);assert.ok(restored.groups.every(g=>g.state.position===8));const bad=structuredClone(s);bad.groups[1].state.members[0].id=bad.groups[0].state.members[0].id;assert.throws(()=>validateGroups(bad,map));const badClock=structuredClone(s);badClock.clock.minutes++;assert.throws(()=>validateGroups(badClock,map));const old=createTravel(map);assert.equal(validateGroups(old,map).groups[0].state,old);});
