import test from 'node:test';import assert from 'node:assert/strict';
import {GAP_ROOF_KINDS,parapetEdges,parapetBlocks} from '../dist/tactics/climbable-roofs.js';
import {blankMap,setTerrain,roofNeighbors,roofValid,neighbors,blockedEdge} from '../dist/tactics/core/maps.js';
import {buildWorld} from '../dist/tactics/hybrid-world.js';
import {EditingDocument} from '../dist/tactics/editor-3d-controller.js';
function fixture(kind,rotated=false){const m=blankMap();m.props=[{kind,x:10,y:10,z:1,rotated}];for(let x=9;x<=12;x++)for(let y=9;y<=12;y++)setTerrain(m,x,y,1,'floor');return m;}
test('solid parapets block their entire perimeter, including legacy climbable IDs',()=>{for(const kind of ['roof-flat-parapet','roof-climbable-flat-parapet']){const m=fixture(kind),edges=parapetEdges(m.props[0]);assert.equal(edges.length,8);for(const {a,b}of edges){assert.ok(blockedEdge(m,a,b));assert.ok(blockedEdge(m,b,a));const key=a.x!==b.x?'e:'+Math.min(a.x,b.x)+':'+a.y+':1':'s:'+a.x+':'+Math.min(a.y,b.y)+':1';m.edges[key]='door';assert.ok(!neighbors(m,b).some(q=>q.x===a.x&&q.y===a.y&&q.z===1));delete m.edges[key];assert.ok(!neighbors(m,b).some(q=>q.x===a.x&&q.y===a.y&&q.z===a.z));setTerrain(m,b.x,b.y,1,'void');assert.equal(roofNeighbors(m,{...b,z:0}).length,0);assert.equal(roofValid(m,{x:b.x,y:b.y,z:0,dx:a.x-b.x,dy:a.y-b.y}),false);}}});
test('every gap and rotation has exactly one traversable one-tile opening, matching visible geometry',()=>{for(const kind of GAP_ROOF_KINDS)for(const rotated of [false,true]){const m=fixture(kind,rotated),solid=parapetEdges({...m.props[0],kind:'roof-flat-parapet'}),open=solid.filter(e=>!parapetBlocks(m,e.a,e.b));assert.equal(open.length,1);const {a,b}=open[0];assert.ok(!blockedEdge(m,a,b));assert.ok(neighbors(m,b).some(q=>q.x===a.x&&q.y===a.y&&q.z===1));assert.equal(buildWorld(m).boxes.filter(b=>b.id.includes(':parapet:')).length,7);for(const e of solid.filter(e=>e!==open[0]))assert.ok(blockedEdge(m,e.a,e.b));}});
test('ladder reaches the exterior landing then enters the roof through the gap; gap does not grant free mantling',()=>{const m=fixture('roof-flat-parapet-gap-west'),low={x:9,y:10,z:0},landing={...low,z:1};m.stairs=[{...low,kind:'ladder'}];assert.ok(neighbors(m,low).some(q=>q.x===9&&q.y===10&&q.z===1));assert.ok(neighbors(m,landing).some(q=>q.x===10&&q.y===10&&q.z===1));setTerrain(m,9,10,1,'void');assert.equal(roofValid(m,{...low,dx:1,dy:0}),false);});
test('gap roof variants survive editor undo, export/import and blocks',()=>{for(const kind of GAP_ROOF_KINDS){const d=new EditingDocument().open(JSON.stringify(blankMap()));assert.ok(d.apply({tool:'roof-tile',start:{x:10,y:10,z:1},options:{propKind:kind,rotated:true}}).ok);const json=d.export();d.undo();assert.equal(d.map.props.length,0);d.redo();assert.equal(d.export(),json);const copy=new EditingDocument().open(json),block=copy.capture(0,0),other=new EditingDocument().open(JSON.stringify(blankMap()));other.place(block,1,1);assert.ok(other.map.props.some(p=>p.kind===kind&&p.rotated));}});

test('gap modules remain available on the decorative fourth roof level',()=>{const d=new EditingDocument().open(JSON.stringify(blankMap()));assert.ok(d.apply({tool:'roof-tile',start:{x:10,y:10,z:3},options:{propKind:GAP_ROOF_KINDS[0]}}).ok);assert.equal(new EditingDocument().open(d.export()).map.canopies[0].kind,GAP_ROOF_KINDS[0]);});
