import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from '../dist/tactics/vendor/three.module.js';import {ANIMAL_MOTION_CATALOG as profiles} from '../dist/tactics/animal-motion-catalog.js';import {createLadderJourney} from '../dist/tactics/ladder-journey.js';import {ladderFrame} from '../dist/tactics/battle-traversal.js';import {towerEntry,towerSlots,towerPost,IRON_LADDER_EXIT} from '../dist/tactics/tower-geometry.js';import {createFurnitureLibrary} from '../dist/tactics/painted-furniture.js';import {towerCenter} from '../dist/tactics/tower-geometry.js';import {toWorld} from '../dist/tactics/hybrid-world.js';
for(const p of profiles.filter(p=>p.id.startsWith('pig')))for(const kind of ['wooden-spotlight-tower','iron-searchlight-ladder-tower'])test(p.id+' '+kind+': supported route, fixed anatomy, shared equipment and reversible ownership',()=>{
 const w=p.create(JSON.parse(fs.readFileSync(new URL('../dist/tactics/'+p.file,import.meta.url)))),source=w.parts.map(p=>Object.fromEntries(Object.entries(p.geometry.attributes).map(([k,a])=>[k,a.array.slice()]))),bonePositions=w.bones.map(b=>b.position.clone()),weapon=w.weapon;try{for(const rotated of [false,true])for(const slot of [0,3])for(const direction of ['up','down']){
 const tower={kind,x:10,y:10,z:1,rotated},bottom=towerEntry(tower),top=towerSlots(tower)[slot];top.towerPost=towerPost(tower,top);const e={tower,direction,from:direction==='up'?bottom:top,to:direction==='up'?top:bottom},m=createLadderJourney(w,p,e,ladderFrame(tower),273);try{
 assert.equal(m.climb.duration,6);assert.equal(m.definition.exitWidth,IRON_LADDER_EXIT.width);for(const t of [0,1]){m.apply(t);assert.ok(w.root.position.distanceTo(new T.Vector3(...toWorld(t?e.to:e.from)))<1e-8);assert.equal(m.climb.equipmentState,'carried');}
 for(const phase of m.phases)for(let i=0;i<=16;i++){const t=(phase.start+(phase.end-phase.start)*i/16)/m.duration,r=m.apply(t);assert.equal(w.weapon,weapon);for(const c of r.contacts)if(c.kind!=='weapon')assert.ok(c.error<1e-5,'contact outside reach');w.bones.forEach((b,i)=>assert.ok(b.position.distanceTo(bonePositions[i])<1e-8,'bone length or bind position changed'));if(phase.label==='Climb'&&i>0&&i<16){assert.equal(m.climb.equipmentState,'stowed');assert.equal(weapon.root.visible,true);}}
 // Upper entry must clear the actual hatch rails and rungs, not only reach its contacts.
 if(!rotated&&slot===0&&direction==='up'&&kind==='wooden-spotlight-tower'){
 const texture=new T.Texture(),library=createFurnitureLibrary(texture,texture),fixture=library.build(kind).root,c=towerCenter(tower);fixture.position.set(c.x,2.12,c.y);fixture.updateMatrixWorld(true);const obstacles=[];fixture.traverse(o=>{if(o.isMesh&&/hatch-back-rail|ladder-rung/.test(o.name)){o.geometry.computeBoundingBox();obstacles.push({name:o.name,box:o.geometry.boundingBox,inv:o.matrixWorld.clone().invert()});}});
 try{const phase=m.phases.find(p=>p.label==='Climb');for(let i=0;i<=40;i++){const progress=.50+i*.0025;m.apply((phase.start+6*progress)/m.duration);for(const mesh of w.parts.filter(p=>/shirt|trousers/.test(p.name)))for(const index of new Set(mesh.geometry.index.array)){const v=mesh.getVertexPosition(index,new T.Vector3()).applyMatrix4(mesh.matrixWorld);for(const o of obstacles){const p=v.clone().applyMatrix4(o.inv),b=o.box;if(b.containsPoint(p)){const depth=Math.min(p.x-b.min.x,b.max.x-p.x,p.y-b.min.y,b.max.y-p.y,p.z-b.min.z,b.max.z-p.z);assert.ok(depth<.005,mesh.name+' intersects '+o.name+' at '+progress+': '+depth);}}}}}finally{library.dispose();texture.dispose();}
 }
 const history=[.17,.33,.63,.81].map(t=>{m.apply(t);return{t,b:w.bones.map(b=>b.getWorldPosition(new T.Vector3()))};});for(const row of history.reverse()){m.apply(row.t);w.bones.forEach((b,i)=>assert.ok(b.getWorldPosition(new T.Vector3()).distanceTo(row.b[i])<1e-8));}
 }finally{m.dispose();m.dispose();w.parts.forEach((p,i)=>{for(const[k,a]of Object.entries(source[i]))assert.deepEqual(p.geometry.attributes[k].array,a,'owned geometry/paint not restored');});}
 }}finally{w.dispose();}
});
