import {generateWorld} from '../dist/tactics/overmap-generator.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {catalog,configurations,canonical,configKey,transformConfig,transformPoint,portPoint,TRANSFORMS,SIZE} from '../dist/tactics/sector-catalog.js';
import {expandPlaceholder} from '../dist/tactics/sector-placeholder.js';
import {validateMap,parseMap} from '../dist/tactics/core/maps.js';
import {undo,redo} from '../dist/tactics/core/editor-model.js';
import {EditingDocument} from '../dist/tactics/editor-3d-controller.js';
const entries=catalog();
test('exhaustive enumeration and D4 canonicalization retain every allowed boundary pattern',()=>{assert.equal(configurations().length,80);const ids=entries.map(e=>e.id);assert.equal(new Set(ids).size,ids.length);for(const raw of configurations()){const key=configKey(canonical(raw).config);assert(entries.some(e=>configKey(e.config)===key)||raw.roads.length===1);for(const t of TRANSFORMS)assert.equal(configKey(canonical(transformConfig(raw,t)).config),key);}assert(entries.some(e=>e.role==='town'&&e.config.feature?.kind==='river'));assert(!entries.some(e=>e.role==='fortress'&&e.config.feature));});
test('every placeholder and orientation is a valid local map with exactly six boundary tiles per road/river port',()=>{for(const e of entries)for(const t of e.allowedTransforms){const map=expandPlaceholder(e,t);assert.deepEqual(validateMap(map,{connectivity:false}),[],e.id+JSON.stringify(t));const c=map.sectorTemplate.config;for(const [kind,ports]of [['river',c.feature?.kind==='river'?c.feature.ports:[]],['road',c.roads.map(side=>({side,slot:1.5}))]])for(const p of ports){const line=p.side==='north'?map.terrain[0]:p.side==='south'?map.terrain[239]:map.terrain.map(r=>r[p.side==='west'?0:239]);const center=p.slot*80,match=v=>kind==='river'?v==='water':v==='ground-asphalt';assert.equal(line.filter(match).length,6,e.id+' '+p.side);assert(line.slice(center-3,center+3).every(match),e.id+' offset');}assert(map.props.length<=512);}});
test('rotation/mirroring transforms actual geometry, markers and contracts together',()=>{const entry=entries.find(e=>e.config.feature?.kind==='river'&&e.config.roads.length);const base=expandPlaceholder(entry);for(const t of TRANSFORMS){const m=expandPlaceholder(entry,t);for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const [a,b]=transformPoint([x+.5,y+.5],t);assert.equal(m.terrain[Math.floor(b)][Math.floor(a)],base.terrain[y][x]);}assert.deepEqual(m.sectorTemplate.config,transformConfig(entry.config,t));}});
test('recipe import, editing undo/redo, full export/import preserve template identity',()=>{const e=entries.find(e=>e.role==='town'),doc=new EditingDocument().open(JSON.stringify(e));assert.equal(doc.size,240);assert(doc.apply({tool:'texture',start:{x:30,y:30,z:0},options:{groundKind:'ground-concrete'}}).ok);assert.equal(doc.map.terrain[30][30],'ground-concrete');undo(doc.editor);doc.refresh();assert.equal(doc.map.terrain[30][30],'yard');redo(doc.editor);doc.refresh();assert.equal(doc.map.terrain[30][30],'ground-concrete');const result=parseMap(doc.export(),{allowDisconnected:true});assert.equal(result.sectorTemplate.id,e.id);assert.equal(new EditingDocument().open(JSON.stringify(result)).map.sectorTemplate.id,e.id);assert.throws(()=>expandPlaceholder({...e,config:{feature:null,roads:['bogus']}}),/Invalid/);assert.throws(()=>expandPlaceholder(e,{turns:99,mirror:false}),/Invalid/);const tutorial=entries.find(e=>e.tutorialStep===1);assert.throws(()=>expandPlaceholder(tutorial,{turns:0,mirror:true}),/does not support/);});
test('checked-in folder recipes match the enumerated contracts',()=>{for(const e of entries){const saved=JSON.parse(fs.readFileSync(new URL('../dist/tactics/sector-library/'+e.id+'/placeholder.json',import.meta.url)));assert.deepEqual(saved.config,e.config);assert(saved.variants.includes('placeholder.json'));}});

test('current generated worlds resolve to catalog geometry and facility roles',()=>{for(const seed of [1,7,42]){const world=generateWorld(seed);for(const sector of world.sectors){if(sector.tutorialStep||sector.role==='tutorial')continue;const feature=sector.routes.find(r=>r.kind==='river'||r.kind==='cliff'),roads=[...new Set(sector.routes.filter(r=>r.kind==='road').flatMap(r=>[r.from.side,r.to.side]).filter(s=>s!=='center'))],config={feature:feature?{kind:feature.kind,ports:[feature.from,feature.to].map(p=>({side:p.side,slot:Math.round(p.offset*3)}))}:null,roads},key=configKey(canonical(config).config);assert(entries.some(e=>!e.tutorialStep&&e.role===sector.role&&configKey(e.config)===key&&JSON.stringify([...e.facilities].sort())===JSON.stringify([...sector.facilities].sort())),seed+' '+sector.role+' '+key);}}});
test('barriers separate banks without pinholes and each gate reconnects them',()=>{const seen=new Set();for(const e of entries){if(!e.config.feature||seen.has(configKey(e.config)))continue;seen.add(configKey(e.config));const m=expandPlaceholder(e),blocked=new Set(m.props.map(p=>p.y*SIZE+p.x));for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++)if(m.terrain[y][x]==='water')blocked.add(y*SIZE+x);const reached=new Set();let components=0;for(let k=0;k<SIZE*SIZE;k++){if(blocked.has(k)||reached.has(k))continue;components++;const queue=[k];reached.add(k);for(let i=0;i<queue.length;i++){const q=queue[i],x=q%SIZE,y=Math.floor(q/SIZE);for(const next of [x? q-1:-1,x<SIZE-1?q+1:-1,y?q-SIZE:-1,y<SIZE-1?q+SIZE:-1])if(next>=0&&!blocked.has(next)&&!reached.has(next)){reached.add(next);queue.push(next);}}}assert.equal(components,e.config.roads.length?1:2,e.id);}});
