import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {QUADRANTS,TOWN,tutorialMap,shelfWidth,townUpper} from '../tools/generate-tutorial-plateau.mjs';
import {parseMap,terrainAt,roofNeighbors,neighbors,passable} from '../dist/tactics/core/maps.js';
const maps=QUADRANTS.map(q=>({q,m:tutorialMap(q)}));
const at=(x,y)=>maps.find(({q})=>q.x===x&&q.y===y).m;
test('four saved variants round-trip as valid maps with closed tiers and summit starts',()=>{for(const {q,m}of maps){const saved=JSON.parse(fs.readFileSync(new URL('../dist/tactics/sector-library/tutorial-step-'+q.step+'/rough-plateau.json',import.meta.url)));assert.deepEqual(saved,m);assert.deepEqual(parseMap(JSON.stringify(saved)),m);assert.equal(m.climbs.length,0);assert.equal(m.stairs.length,0);assert.ok(!m.props.some(p=>p.kind.startsWith('ramp')));assert.ok(m.props.length<=1024);for(const p of [...m.starts,...m.exits]){assert.equal(p.z,2);assert.ok(passable(m,p));}for(const p of m.props){const low={x:p.x,y:p.y,z:p.z},high={...low,z:p.z+1};assert.equal(passable(m,low),false);assert.equal(roofNeighbors(m,high).length,0);assert.ok(neighbors(m,high).every(n=>n.z===high.z));}}});
test('terrain and cliff bands match across all four shared edges on every level',()=>{for(const k of [0,1])for(let n=0;n<240;n++)for(let z=0;z<3;z++){assert.equal(terrainAt(at(0,k),239,n,z),terrainAt(at(1,k),0,n,z));assert.equal(terrainAt(at(k,0),n,239,z),terrainAt(at(k,1),n,0,z));}const cliff=(m,x,y,z)=>m.props.some(p=>p.x===x&&p.y===y&&p.z===z);for(const k of [0,1])for(let n=0;n<240;n++)for(let z=0;z<2;z++){assert.equal(cliff(at(0,k),239,n,z),cliff(at(1,k),0,n,z));assert.equal(cliff(at(k,0),n,239,z),cliff(at(k,1),n,0,z));}});
test('outer seams sit 24 tiles from outside edges',()=>{const m=at(1,1);assert.equal(terrainAt(m,216,0,1),'void');assert.notEqual(terrainAt(m,215,0,1),'void');assert.equal(terrainAt(m,0,216,1),'void');assert.notEqual(terrainAt(m,0,215,1),'void');});
test('shelf varies from zero to two tiles and upper terrain stays within the lower footprint',()=>{const widths=new Set();for(const {q,m}of maps)for(let y=0;y<240;y++)for(let x=0;x<240;x++){const top=terrainAt(m,x,y,2),lower=terrainAt(m,x,y,1);if(top!=='void')assert.equal(m.terrain[y][x]==='ground-grass'&&!m.props.some(p=>p.x===x&&p.y===y&&p.z===0),false);if(lower==='ground-dirt'){widths.add(shelfWidth(q.x*240+x,q.y*240+y));let nearest=Infinity;for(let dy=-3;dy<=3;dy++)for(let dx=-3;dx<=3;dx++)if(terrainAt(m,x+dx,y+dy,2)!=='void')nearest=Math.min(nearest,Math.abs(dx)+Math.abs(dy));assert.ok(nearest<=2,'shelf wider than two tiles at '+x+','+y);}}assert.ok(widths.has(0)&&widths.has(1)&&widths.has(2));});
test('northwest town approach includes the sketched upper-tier curve and reaches its travel marker',()=>{const m=at(0,0);for(let x=0;x<240;x++)assert.equal(terrainAt(m,x,0,2)!=='void',townUpper(x,0)||(x>=80+shelfWidth(x,0)&&x<160-shelfWidth(x,0)));assert.deepEqual(m.exits,[{x:120,y:0,z:2}]);assert.deepEqual(m.sectorTemplate.plateau.townApproach.bounds,[80,160]);});

test('sector four west face stays at the 24 tile margin',()=>{const m=at(0,0);for(let y=24;y<240;y++){assert.ok(m.props.some(p=>p.x===24&&p.y===y&&p.z===0));assert.equal(terrainAt(m,23,y,2),'void');}});
test('town variant validates and cliff enters 24 tiles deep with a matching southern seam',()=>{const town=tutorialMap(TOWN),nw=at(0,0),saved=JSON.parse(fs.readFileSync(new URL('../dist/tactics/sector-library/tutorial-step-5/rough-plateau.json',import.meta.url)));assert.deepEqual(saved,town);assert.deepEqual(parseMap(JSON.stringify(town)),town);for(let x=0;x<240;x++)for(let z=0;z<3;z++)assert.equal(terrainAt(town,x,239,z),terrainAt(nw,x,0,z));assert.equal(terrainAt(town,120,215,1),'void');assert.notEqual(terrainAt(town,120,216,1),'void');assert.equal(town.climbs.length,0);assert.equal(town.stairs.length,0);});

test('town sketch adds lower-tier shapes and an upper-tier southern curve without raising the surrounding ground',()=>{const m=tutorialMap(TOWN);for(const [x,y]of [[40,60],[45,185]]){assert.equal(terrainAt(m,x,y,1),'ground-dirt');assert.equal(terrainAt(m,x,y,2),'void');}assert.equal(terrainAt(m,50,230,2),'ground-grass');assert.equal(terrainAt(m,180,180,0),'ground-grass');assert.equal(terrainAt(m,180,180,1),'void');for(let y=0;y<240;y++)for(let x=0;x<240;x++)assert.equal(terrainAt(m,x,y,0)==='ground-asphalt',(y>=117&&y<=122)||(x>=117&&x<=122&&y<120));for(const [x,y]of [[0,120],[239,120],[120,0],[120,120]])assert.ok(passable(m,{x,y,z:0}));});
