import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH||'playwright'),base=process.env.REVIEW_URL||'http://127.0.0.1:4433/tactics/',out=new URL('../artifacts/casualty-review/',import.meta.url);fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1600,height:1130}}),errors=[],results=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
try{
 for(const animal of ['horse','goat','bull','cow','donkey','sheep','skunk','pig-foreman','pig-director','rabbit','dog','hen'])for(const outfit of ['normal','red-hats']){
  await page.goto(base+'animal-casualty-review.html?animal='+animal+'&outfit='+outfit);await page.waitForFunction(()=>window.casualtyStudy?.ready);
  for(const scale of ['130','58']){await page.selectOption('#scale',scale);const rows=await page.evaluate(()=>casualtyStudy.rows);assert.equal(rows.length,3);for(const row of rows){assert.equal(row.weaponVisible,false);assert.ok(Math.abs(row.bounds.min[1]-.012)<1e-5);}await page.screenshot({path:fileURLToPath(new URL(`${animal}-${outfit}-${scale}.png`,out))});results.push({animal,outfit,scale});}
  // Validate the fitted cap as well as the original worker surfaces.
  const capMin=await page.evaluate(async()=>{const cap=casualtyStudy.item.cap?.mesh;if(!cap)return null;const T=await import('./vendor/three.module.js'),v=new T.Vector3();let min=Infinity;for(const pose of [{down:1},{down:1,stable:1},{down:1,dead:1}]){casualtyStudy.apply({pose,heading:0,blend:0,distance:0});for(let i=0;i<cap.geometry.attributes.position.count;i++){v.fromBufferAttribute(cap.geometry.attributes.position,i).applyMatrix4(cap.matrixWorld);min=Math.min(min,v.y);}}casualtyStudy.render();return min;});assert.ok(capMin===null||capMin>=-.015,animal+' cap intersects floor '+capMin);
  for(const route of ['standing:bleeding','kneeling:dead','prone:dead','bleeding:stable','bleeding:dead','stable:standing','stable:kneeling','stable:prone']){await page.selectOption('#route',route);await page.selectOption('#view','strip');assert.equal(await page.evaluate(()=>casualtyStudy.rows.length),12);if(outfit==='normal')await page.screenshot({path:fileURLToPath(new URL(`${animal}-${route.replace(':','-')}.png`,out))});}
  await page.selectOption('#view','transition');await page.check('#reduced');await page.evaluate(()=>{document.getElementById('progress').value=100;casualtyStudy.render();});assert.equal(await page.evaluate(()=>casualtyStudy.rows[0].pose.down),0);
 }
 // Controlled renderer-state fixture: floor placement, reuse and prone recovery.
 // Core damage/medical rules are covered by their existing simulation tests.
 await page.goto(base+'battle-3d.html');await page.waitForFunction(()=>window.battle3d?.renderer.models.size>=4);await page.emulateMedia({reducedMotion:'reduce'});
 for(const casualty of ['bleeding','stable','dead']){await page.evaluate(c=>{const u=battle3d.state.units[0];u.hp=0;u.casualty=c;u.stance='prone';u.bleedTurns=3;battle3d.state.revision++;},casualty);await page.waitForFunction(c=>battle3d.renderer.motion.sample(battle3d.state.units[0]).posture===c,casualty);const result=await page.evaluate(()=>{const m=battle3d.renderer.models.get(0);return {weapon:m.worker.weapon.root.visible,triangles:m.worker.diagnostics().triangles};});assert.equal(result.weapon,false);assert.ok(result.triangles>9000);}
 await page.evaluate(()=>{const u=battle3d.state.units[0];u.hp=5;u.casualty=null;battle3d.state.revision++;});await page.waitForFunction(()=>battle3d.renderer.motion.sample(battle3d.state.units[0]).pose.prone===1);assert.equal(await page.evaluate(()=>battle3d.renderer.models.get(0).worker.weapon.root.visible),true);
 const elevation=await page.evaluate(async()=>{const {toWorld}=await import('./hybrid-world.js'),r=battle3d.renderer,u={...battle3d.state.units[0],hp:0,casualty:'dead',z:2};r.motion.update([u],performance.now(),true);const actor=r.actor(u);return {actual:actor.position.toArray(),expected:toWorld(u)};});assert.deepEqual(elevation.actual,elevation.expected);
 await page.screenshot({path:fileURLToPath(new URL('production-recovery.png',out))});assert.deepEqual(errors,[]);fs.writeFileSync(new URL('results.json',out),JSON.stringify({configurations:results.length,transitionStrips:192,results,productionRecovery:true,errors},null,2));console.log(JSON.stringify({configurations:results.length,transitionStrips:192,errors}));
}finally{await browser.close();}
