"""Rebuild calibrated crop bounds for the additional environment collections."""
import json
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
assets = root / 'dist/assets/environment'
art = {}
for folder in ['facility', 'hospital', 'containers', 'loot']:
    for path in sorted((assets / folder).glob('*.png')):
        alpha = Image.open(path).convert('RGBA').getchannel('A')
        art[path.stem] = {'file': f'{folder}/{path.name}', 'crop': alpha.point(lambda a: 255 if a >= 64 else 0).getbbox()}
for name in ['tree-broadleaf', 'tree-pine', 'bush', 'reeds']:
    path = assets / 'foliage' / (name + '.png')
    alpha = Image.open(path).convert('RGBA').getchannel('A')
    art[name] = {'file': f'foliage/{path.name}', 'crop': alpha.point(lambda a: 255 if a >= 64 else 0).getbbox()}
path = assets / 'fence-chainlink-cut.png'
for name in ['tree-broadleaf', 'tree-pine']:
    art[name + '-large'] = dict(art[name])
for name in ['roof-corrugated-flat', 'roof-corrugated-sloped', 'roof-flat-parapet']:
    roof = assets / (name + '.png')
    alpha = Image.open(roof).convert('RGBA').getchannel('A')
    art[name] = {'file': roof.name, 'crop': alpha.point(lambda a: 255 if a >= 64 else 0).getbbox()}
art['fence-cut'] = {'file': path.name, 'crop': Image.open(path).convert('RGBA').getchannel('A').point(lambda a: 255 if a >= 64 else 0).getbbox()}
# Pixel anchors at each barrier's foot, plus visible post height; mapped onto either tile edge.
for key in ['jail-bars', 'jail-door-closed']:
    art[key].update(baseline=[350, 1190, 907, 950, 900], height=62)
art['fence-cut'].update(baseline=[230, 1165, 1110, 694, 530], height=44)
(root / 'dist/tactics/prop-art.js').write_text('// Generated by tools/catalog-environment.py; alpha >= 64.\nexport const PROP_ART = ' + json.dumps(art, indent=2) + ';\n', encoding='utf-8')
