import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH||'playwright');const browser=await chromium.launch({channel:'msedge',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4323/tactics/battle-3d.html');await page.waitForFunction(()=>window.battle3d?.state,null,{timeout:120000});await page.waitForFunction(()=>battle3d.renderer.models.size>=4,null,{timeout:120000});
await page.evaluate(async()=>{const s=battle3d.state,u=s.units[0],v=s.units[1];s.phase='player';s.engaged=true;s.rules.awareness=false;s.queue=[];u.ap=v.ap=18;v.x=u.x+1;v.y=u.y;delete s.edges['e:'+u.x+':'+u.y];s.revision++;});
await page.click('#character');await page.locator('.dossier-roster').getByRole('button',{name:'Anya',exact:true}).click();const picks=page.locator('.dossier-backpack > .dossier-item').filter({has:page.locator('strong',{hasText:'Lockpick set'})});await picks.getByRole('combobox',{name:'Give Lockpick set to'}).selectOption('0');await picks.getByRole('button',{name:/^Give/}).click();assert.equal(await page.evaluate(()=>battle3d.state.units[0].pack.some(i=>i.kind==='lockpicks')),true);
await page.locator('.dossier-roster').getByRole('button',{name:'Yakov',exact:true}).click();const med=page.locator('.dossier-backpack > .dossier-item').filter({has:page.locator('strong',{hasText:'Medical kit'})});await med.getByRole('button',{name:/^Drop/}).click();assert.equal(await page.evaluate(()=>battle3d.state.units[0].medkits),0);const groundMed=page.locator('.dossier-loot section > .dossier-item').filter({has:page.locator('strong',{hasText:'Medical kit'})});await groundMed.getByRole('button',{name:/^Take/}).click();assert.equal(await page.evaluate(()=>battle3d.state.units[0].medkits),1);
const held=page.locator('.dossier-equipment > .dossier-item').filter({has:page.locator('strong',{hasText:'AK-47'})});await held.getByRole('button',{name:'To backpack'}).click();assert.equal(await page.evaluate(()=>battle3d.state.units[0].weapon),'hands');await page.click('#character');const gun=page.locator('.dossier-backpack > .dossier-item').filter({has:page.locator('strong',{hasText:'AK-47'})});await gun.getByRole('button',{name:/Ready 1/}).click();await page.waitForFunction(()=>!battle3d.renderer.busy,null,{timeout:120000});assert.equal(await page.evaluate(()=>battle3d.state.units[0].weapon),'assault');
await page.evaluate(()=>{const s=battle3d.state,u=s.units[0];u.ap=18;u.stats.dexterity=100;s.interactionSeed=1;const key='s:'+u.x+':'+u.y;s.edges[key]='door-steel-closed';s.edgeLocks[key]=50;s.revision++;});await page.getByRole('button',{name:/Pick lock/}).click();assert.equal(await page.evaluate(()=>Object.keys(battle3d.state.edgeLocks).length),0);
await page.click('#character');fs.mkdirSync('artifacts/inventory',{recursive:true});await page.screenshot({path:'artifacts/inventory/desktop.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/inventory/mobile.png'});assert.ok(await page.evaluate(()=>{const d=document.querySelector('#character-screen');return d.scrollWidth<=d.clientWidth;}));assert.deepEqual(errors,[]);console.log(JSON.stringify({transfer:true,drop:true,pickup:true,stow:true,draw:true,lockedDoor:true,mobile:true,errors}));}finally{await browser.close();}
